services:
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/history"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - net

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - net

  logging-service:
    build: ./logging-service
    container_name: logger
    depends_on:
      - redis
    networks:
      - net

networks:
  net:
